PACKAGE_NAME="vcan_usb"
PACKAGE_VERSION="1.1.4"
BUILT_MODULE_NAME[0]="vcan_usb"
DEST_MODULE_LOCATION[0]="/kernel/drivers/net/can/usb"
AUTOINSTALL="yes"
MAKE[0]="make KDIR=/lib/modules/${kernelver}/build"
CLEAN="make KDIR=/lib/modules/${kernelver}/build clean"
