[metadata]
name = vcan-usb
version = 0.2.0
description = python-can backend for HPMicro VCAN USB adapters
long_description = file: README.md
long_description_content_type = text/markdown

[options]
packages = find:
python_requires = >=3.10
install_requires =
    python-can>=4.3
    pyusb>=1.2
    libusb1>=3.4

[options.entry_points]
can.interface =
    vcan_usb = vcan_usb.bus:vcan_usb_bus
